version: '3'
services:
  web:
    build: .
    command: npm run prod
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      PORT : $PORT