version: '3.7'
services:
  database:
    image: 'mongo'
    container_name: 'uSocialDB'
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 3030:27017
volumes:
  mongodb_data_container: